# Change the default Omarchy look'n'feel

# https://wiki.hypr.land/Configuring/Basics/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 0
    gaps_out = 0
    border_size = 1

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 2
    active_opacity = 0.94

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    dim_inactive = true
    dim_strength = 0.15
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#animations
animations {
    # Disable all animations
    # enabled = no
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/
scrolling {
    # See only one column per screen instead of two
    # column_width = 0.97
}
