[env]
TERM = "xterm-256color"

[font]
size = 8.7

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control"

[window]
opacity = 0.8
